server:
  port: 8080

spring:
  application:
    name: mybatisplus
  datasource:
    name: mybatisplus
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=true
    username: root
    password: 123123123
    #druid
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis-plus:
  # resource： classpath:/mapper/*.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # entity class
  typeAliasesPackage: com.mybatisplus.demo.entity
  global-config:
    db-config:
      id-type: 3
      field-strategy: 2
      db-column-underline: true
      refresh-mapper: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

logging:
  level:
    com.mybatisplus.demo: debug